version: '{build}'
image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK
branches:
  only:
    - main
build: off
install:
  - cmd: choco install maven -y -f
  - cmd: refreshenv
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - java -jar ./cardDeliveryTest/artifacts/app-card-delivery.jar &
build_script:
  - mvn clean compile exec:java -Denvironment=service "-Dcucumber.options=--tags @card-delivery-replanning" --add-opens java.base/java.lang=ALL-UNNAMED test
