version: '{build}'
os: Windows Server 2012
stack: jdk 8
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - main
build: off
install:
  - cmd: choco install maven -y -f
  - cmd: refreshenv
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - java -jar .cardDeliveryTest/artifacts/app-card-delivery.jar &
build_script:
  - mvn clean compile exec:java -Denvironment=service "-Dcucumber.options=--tags @card-delivery-replanning" test
